### ISSUE TITLE
可以跟您请教下怎么轻量化姿态估计模型吗？

### ISSUE THREAD

**Issue by LRY89757** [12-10-8/ncnn-android-pose#3]

**Comment by LRY89757** [comment]
或者说您原本模型是多大，我看您使用ncnn量化过后的模型只有17MB，请问您量化前大概会有多大呢

**Comment by 12-10-8** [comment]
姿态估计ncnn后是7-8M，pytorch的原本模型20多，首先是转为onnx就是7-8M了，然后在转为ncnn的param和bin文件，几乎是一样大的，量化后会更小，但我怕精度损失会比较严重因此没有采用ncnn的优化。关于设计轻量化模型就是把resnet主干网络替换成mobilenet一类的轻量级backbone，这个可以自己尝试设计，很多论文也有类似的方法

**Comment by LRY89757** [comment]
> 姿态估计ncnn后是7-8M，pytorch的原本模型20多，首先是转为onnx就是7-8M了，然后在转为ncnn的param和bin文件，几乎是一样大的，量化后会更小，但我怕精度损失会比较严重因此没有采用ncnn的优化。关于设计轻量化模型就是把resnet主干网络替换成mobilenet一类的轻量级backbone，这个可以自己尝试设计，很多论文也有类似的方法

非常感谢您！我从您这里学到了很多，也希望以后能与您继续交流！🥳
